
//Login details actions
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

//user device token  actions
export const USERTOKEN_USER_START = 'USERTOKEN_USER_START';
export const USERTOKEN_USER_SUCCESS = 'USERTOKEN_USER_SUCCESS';
export const USERTOKEN_USER_ERROR = 'USERTOKEN_USER_ERROR';
//aloow notifications actions
export const ALLOW_NOTIFICATIONS_USER_START = 'ALLOW_NOTIFICATIONS_USER_START';
export const ALLOW_NOTIFICATIONS_USER_SUCCESS = 'ALLOW_NOTIFICATIONS_USER_SUCCESS';
export const ALLOW_NOTIFICATIONS_USER_ERROR = 'ALLOW_NOTIFICATIONS_USER_ERROR';

//Read notifications actions
export const READ_NOTIFICATIONS_START = 'READ_NOTIFICATIONS_START';
export const READ_NOTIFICATIONS_SUCCESS = 'READ_NOTIFICATIONS_SUCCESS';
export const READ_NOTIFICATIONS_ERROR = 'READ_NOTIFICATIONS_ERROR';

// load notifications Details 
export const LOAD_NOTIFICATIONS_DETAILS_START = 'LOAD_NOTIFICATIONS_DETAILS_START';
export const LOAD_NOTIFICATIONS_DETAILS_SUCCESS = 'LOAD_NOTIFICATIONS_DETAILS_SUCCESS';
export const LOAD_NOTIFICATIONS_DETAILS_ERROR = 'LOAD_NOTIFICATIONS_DETAILS_ERROR';

//dashboard details actions
export const LOAD_DASHBOARD_DETAILS_START = "LOAD_DASHBOARD_DETAILS_START";
export const LOAD_DASHBOARD_DETAILS_SUCCESS = "LOAD_DASHBOARD_DETAILS_SUCCESS";
export const LOAD_DASHBOARD_DETAILS_ERROR = "LOAD_DASHBOARD_DETAILS_ERROR";

//personal details or user details actions
export const LOAD_USERS_START = "LOAD_USERS_START";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR";

export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';


//personal details or user details actions
export const LOAD_PROFILE_START = "LOAD_PROFILE_START";
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS";
export const LOAD_PROFILE_ERROR = "LOAD_PROFILE_ERROR";

export const CREATE_PROFILE_START = 'CREATE_PROFILE_START';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_ERROR = 'CREATE_PROFILE_ERROR';

export const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

//family details actions
export const LOAD_FAMILY_DETAILS_START = 'LOAD_FAMILY_DETAILS_START';
export const LOAD_FAMILY_DETAILS_SUCCESS = 'LOAD_FAMILY_DETAILS_SUCCESS';
export const LOAD_FAMILY_DETAILS_ERROR = 'LOAD_FAMILY_DETAILS_ERROR';

export const CREATE_FAMILY_DETAILS_START = 'CREATE_FAMILY_DETAILS_START';
export const CREATE_FAMILY_DETAILS_SUCCESS = 'CREATE_FAMILY_DETAILS_SUCCESS';
export const CREATE_FAMILY_DETAILS_ERROR = 'CREATE_FAMILY_DETAILS_ERROR';

export const UPDATE_FAMILY_DETAILS_START = 'UPDATE_FAMILY_DETAILS_START';
export const UPDATE_FAMILY_DETAILS_SUCCESS = 'UPDATE_FAMILY_DETAILS_SUCCESS';
export const UPDATE_FAMILY_DETAILS_ERROR = 'UPDATE_FAMILY_DETAILS_ERROR';

export const DELETE_FAMILY_DETAILS_START = 'DELETE_FAMILY_DETAILS_START';
export const DELETE_FAMILY_DETAILS_SUCCESS = 'DELETE_FAMILY_DETAILS_SUCCESS';
export const DELETE_FAMILY_DETAILS_ERROR = 'DELETE_FAMILY_DETAILS_ERROR';


//emergency details actions
export const LOAD_EMERGENCY_DETAILS_START = 'LOAD_EMERGENCY_DETAILS_START';
export const LOAD_EMERGENCY_DETAILS_SUCCESS = 'LOAD_EMERGENCY_DETAILS_SUCCESS';
export const LOAD_EMERGENCY_DETAILS_ERROR = 'LOAD_EMERGENCY_DETAILS_ERROR';

export const CREATE_EMERGENCY_DETAILS_START = 'CREATE_EMERGENCY_DETAILS_START';
export const CREATE_EMERGENCY_DETAILS_SUCCESS = 'CREATE_EMERGENCY_DETAILS_SUCCESS';
export const CREATE_EMERGENCY_DETAILS_ERROR = 'CREATE_EMERGENCY_DETAILS_ERROR';

export const UPDATE_EMERGENCY_DETAILS_START = 'UPDATE_EMERGENCY_DETAILS_START';
export const UPDATE_EMERGENCY_DETAILS_SUCCESS = 'UPDATE_EMERGENCY_DETAILS_SUCCESS';
export const UPDATE_EMERGENCY_DETAILS_ERROR = 'UPDATE_EMERGENCY_DETAILS_ERROR';

export const DELETE_EMERGENCY_DETAILS_START = 'DELETE_EMERGENCY_DETAILS_START';
export const DELETE_EMERGENCY_DETAILS_SUCCESS = 'DELETE_EMERGENCY_DETAILS_SUCCESS';
export const DELETE_EMERGENCY_DETAILS_ERROR = 'DELETE_EMERGENCY_DETAILS_ERROR';


//WorkExpeience details actions
export const LOAD_WORKEXP_DETAILS_START = 'LOAD_WORKEXP_DETAILS_START';
export const LOAD_WORKEXP_DETAILS_SUCCESS = 'LOAD_WORKEXP_DETAILS_SUCCESS';
export const LOAD_WORKEXP_DETAILS_ERROR = 'LOAD_WORKEXP_DETAILS_ERROR';

export const CREATE_WORKEXP_DETAILS_START = 'CREATE_WORKEXP_DETAILS_START';
export const CREATE_WORKEXP_DETAILS_SUCCESS = 'CREATE_WORKEXP_DETAILS_SUCCESS';
export const CREATE_WORKEXP_DETAILS_ERROR = 'CREATE_WORKEXP_DETAILS_ERROR';

export const UPDATE_WORKEXP_DETAILS_START = 'UPDATE_WORKEXP_DETAILS_START';
export const UPDATE_WORKEXP_DETAILS_SUCCESS = 'UPDATE_WORKEXP_DETAILS_SUCCESS';
export const UPDATE_WORKEXP_DETAILS_ERROR = 'UPDATE_WORKEXP_DETAILS_ERROR';

export const DELETE_WORKEXP_DETAILS_START = 'DELETE_WORKEXP_DETAILS_START';
export const DELETE_WORKEXP_DETAILS_SUCCESS = 'DELETE_WORKEXP_DETAILS_SUCCESS';
export const DELETE_WORKEXP_DETAILS_ERROR = 'DELETE_WORKEXP_DETAILS_ERROR';

//skills details actions
export const LOAD_SKILLS_DETAILS_START = 'LOAD_SKILLS_DETAILS_START';
export const LOAD_SKILLS_DETAILS_SUCCESS = 'LOAD_SKILLS_DETAILS_SUCCESS';
export const LOAD_SKILLS_DETAILS_ERROR = 'LOAD_SKILLS_DETAILS_ERROR';

export const CREATE_SKILLS_DETAILS_START = 'CREATE_SKILLS_DETAILS_START';
export const CREATE_SKILLS_DETAILS_SUCCESS = 'CREATE_SKILLS_DETAILS_SUCCESS';
export const CREATE_SKILLS_DETAILS_ERROR = 'CREATE_SKILLS_DETAILS_ERROR';

export const UPDATE_SKILLS_DETAILS_START = 'UPDATE_SKILLS_DETAILS_START';
export const UPDATE_SKILLS_DETAILS_SUCCESS = 'UPDATE_SKILLS_DETAILS_SUCCESS';
export const UPDATE_SKILLS_DETAILS_ERROR = 'UPDATE_SKILLS_DETAILS_ERROR';

export const DELETE_SKILLS_DETAILS_START = 'DELETE_SKILLS_DETAILS_START';
export const DELETE_SKILLS_DETAILS_SUCCESS = 'DELETE_SKILLS_DETAILS_SUCCESS';
export const DELETE_SKILLS_DETAILS_ERROR = 'DELETE_SKILLS_DETAILS_ERROR';

//dailystatus details actions
export const LOAD_DAILYSTATUS_DETAILS_START = 'LOAD_DAILYSTATUS_DETAILS_START';
export const LOAD_DAILYSTATUS_DETAILS_SUCCESS = 'LOAD_DAILYSTATUS_DETAILS_SUCCESS';
export const LOAD_DAILYSTATUS_DETAILS_ERROR = 'LOAD_DAILYSTATUS_DETAILS_ERROR';

export const CREATE_DAILYSTATUS_DETAILS_START = 'CREATE_DAILYSTATUS_DETAILS_START';
export const CREATE_DAILYSTATUS_DETAILS_SUCCESS = 'CREATE_DAILYSTATUS_DETAILS_SUCCESS';
export const CREATE_DAILYSTATUS_DETAILS_ERROR = 'CREATE_DAILYSTATUS_DETAILS_ERROR';

export const UPDATE_DAILYSTATUS_DETAILS_START = 'UPDATE_DAILYSTATUS_DETAILS_START';
export const UPDATE_DAILYSTATUS_DETAILS_SUCCESS = 'UPDATE_DAILYSTATUS_DETAILS_SUCCESS';
export const UPDATE_DAILYSTATUS_DETAILS_ERROR = 'UPDATE_DAILYSTATUS_DETAILS_ERROR';

export const DELETE_DAILYSTATUS_DETAILS_START = 'DELETE_DAILYSTATUS_DETAILS_START';
export const DELETE_DAILYSTATUS_DETAILS_SUCCESS = 'DELETE_DAILYSTATUS_DETAILS_SUCCESS';
export const DELETE_DAILYSTATUS_DETAILS_ERROR = 'DELETE_DAILYSTATUS_DETAILS_ERROR';

//hoursentry details actions
export const LOAD_HOURSENTRY_DETAILS_START = 'LOAD_HOURSENTRY_DETAILS_START';
export const LOAD_HOURSENTRY_DETAILS_SUCCESS = 'LOAD_HOURSENTRY_DETAILS_SUCCESS';
export const LOAD_HOURSENTRY_DETAILS_ERROR = 'LOAD_HOURSENTRY_DETAILS_ERROR';

export const CREATE_HOURSENTRY_DETAILS_START = 'CREATE_HOURSENTRY_DETAILS_START';
export const CREATE_HOURSENTRY_DETAILS_SUCCESS = 'CREATE_HOURSENTRY_DETAILS_SUCCESS';
export const CREATE_HOURSENTRY_DETAILS_ERROR = 'CREATE_HOURSENTRY_DETAILS_ERROR';

export const UPDATE_HOURSENTRY_DETAILS_START = 'UPDATE_HOURSENTRY_DETAILS_START';
export const UPDATE_HOURSENTRY_DETAILS_SUCCESS = 'UPDATE_HOURSENTRY_DETAILS_SUCCESS';
export const UPDATE_HOURSENTRY_DETAILS_ERROR = 'UPDATE_HOURSENTRY_DETAILS_ERROR';

export const DELETE_HOURSENTRY_DETAILS_START = 'DELETE_HOURSENTRY_DETAILS_START';
export const DELETE_HOURSENTRY_DETAILS_SUCCESS = 'DELETE_HOURSENTRY_DETAILS_SUCCESS';
export const DELETE_HOURSENTRY_DETAILS_ERROR = 'DELETE_HOURSENTRY_DETAILS_ERROR';

//myprojects details actions
export const LOAD_MYPROJECTS_DETAILS_START = 'LOAD_MYPROJECTS_DETAILS_START';
export const LOAD_MYPROJECTS_DETAILS_SUCCESS = 'LOAD_MYPROJECTS_DETAILS_SUCCESS';
export const LOAD_MYPROJECTS_DETAILS_ERROR = 'LOAD_MYPROJECTS_DETAILS_ERROR';

export const CREATE_MYPROJECTS_DETAILS_START = 'CREATE_MYPROJECTS_DETAILS_START';
export const CREATE_MYPROJECTS_DETAILS_SUCCESS = 'CREATE_MYPROJECTS_DETAILS_SUCCESS';
export const CREATE_MYPROJECTS_DETAILS_ERROR = 'CREATE_MYPROJECTS_DETAILS_ERROR';

export const UPDATE_MYPROJECTS_DETAILS_START = 'UPDATE_MYPROJECTS_DETAILS_START';
export const UPDATE_MYPROJECTS_DETAILS_SUCCESS = 'UPDATE_MYPROJECTS_DETAILS_SUCCESS';
export const UPDATE_MYPROJECTS_DETAILS_ERROR = 'UPDATE_MYPROJECTS_DETAILS_ERROR';

export const DELETE_MYPROJECTS_DETAILS_START = 'DELETE_MYPROJECTS_DETAILS_START';
export const DELETE_MYPROJECTS_DETAILS_SUCCESS = 'DELETE_MYPROJECTS_DETAILS_SUCCESS';
export const DELETE_MYPROJECTS_DETAILS_ERROR = 'DELETE_MYPROJECTS_DETAILS_ERROR';

//leaves details actions
export const LOAD_LEAVES_DETAILS_START = 'LOAD_LEAVES_DETAILS_START';
export const LOAD_LEAVES_DETAILS_SUCCESS = 'LOAD_LEAVES_DETAILS_SUCCESS';
export const LOAD_LEAVES_DETAILS_ERROR = 'LOAD_LEAVES_DETAILS_ERROR';

export const CREATE_LEAVES_DETAILS_START = 'CREATE_LEAVES_DETAILS_START';
export const CREATE_LEAVES_DETAILS_SUCCESS = 'CREATE_LEAVES_DETAILS_SUCCESS';
export const CREATE_LEAVES_DETAILS_ERROR = 'CREATE_LEAVES_DETAILS_ERROR';

export const UPDATE_LEAVES_DETAILS_START = 'UPDATE_LEAVES_DETAILS_START';
export const UPDATE_LEAVES_DETAILS_SUCCESS = 'UPDATE_LEAVES_DETAILS_SUCCESS';
export const UPDATE_LEAVES_DETAILS_ERROR = 'UPDATE_LEAVES_DETAILS_ERROR';

export const DELETE_LEAVES_DETAILS_START = 'DELETE_LEAVES_DETAILS_START';
export const DELETE_LEAVES_DETAILS_SUCCESS = 'DELETE_LEAVES_DETAILS_SUCCESS';
export const DELETE_LEAVES_DETAILS_ERROR = 'DELETE_LEAVES_DETAILS_ERROR';

//bank details actions
export const LOAD_BANK_DETAILS_START = 'LOAD_BANK_DETAILS_START';
export const LOAD_BANK_DETAILS_SUCCESS = 'LOAD_BANK_DETAILS_SUCCESS';
export const LOAD_BANK_DETAILS_ERROR = 'LOAD_BANK_DETAILS_ERROR';

export const CREATE_BANK_DETAILS_START = 'CREATE_BANK_DETAILS_START';
export const CREATE_BANK_DETAILS_SUCCESS = 'CREATE_BANK_DETAILS_SUCCESS';
export const CREATE_BANK_DETAILS_ERROR = 'CREATE_BANK_DETAILS_ERROR';

export const UPDATE_BANK_DETAILS_START = 'UPDATE_BANK_DETAILS_START';
export const UPDATE_BANK_DETAILS_SUCCESS = 'UPDATE_BANK_DETAILS_SUCCESS';
export const UPDATE_BANK_DETAILS_ERROR = 'UPDATE_BANK_DETAILS_ERROR';

export const DELETE_BANK_DETAILS_START = 'DELETE_BANK_DETAILS_START';
export const DELETE_BANK_DETAILS_SUCCESS = 'DELETE_BANK_DETAILS_SUCCESS';
export const DELETE_BANK_DETAILS_ERROR = 'DELETE_BANK_DETAILS_ERROR';

//getting current week details
export const LOAD_CURRENT_WEEK_DETAILS_START = 'LOAD_CURRENT_WEEK_DETAILS_START';
export const LOAD_CURRENT_WEEK_DETAILS_SUCCESS = 'LOAD_CURRENT_WEEK_DETAILS_SUCCESS';
export const LOAD_CURRENT_WEEK_DETAILS_ERROR = 'LOAD_CURRENT_WEEK_DETAILS_ERROR';


//getting User list details
export const LOAD_USERS_LIST_START = 'LOAD_USERS_LIST_START';
export const LOAD_USERS_LIST_SUCCESS = 'LOAD_USERS_LIST_SUCCESS';
export const LOAD_USERS_LIST_ERROR = 'LOAD_USERS_LIST_ERROR';



//expert creation details   
export const CREATE_EXPERT_CREATION_START= 'CREATE_EXPERT_CREATION_START';
export const CREATE_EXPERT_CREATION_SUCCESS = 'CREATE_EXPERT_CREATION_SUCCESS';
export const CREATE_EXPERT_CREATION_ERROR = 'CREATE_EXPERT_CREATION_ERROR';


//expert creation details   
export const CREATE_LEAVE_BANK_START= 'CREATE_LEAVE_BANK_START';
export const CREATE_LEAVE_BANK_SUCCESS = 'CREATE_LEAVE_BANK_SUCCESS';
export const CREATE_LEAVE_BANK_ERROR = 'CREATE_LEAVE_BANK_ERROR';

export const LOAD_LEAVE_BANK_START = 'LOAD_LEAVE_BANK_START';
export const LOAD_LEAVE_BANK_SUCCESS = 'LOAD_LEAVE_BANK_SUCCESS';
export const LOAD_LEAVE_BANK_ERROR = 'LOAD_LEAVE_BANK_ERROR';

export const UPDATE_LEAVE_BANK_START = 'UPDATE_LEAVE_BANK_START';
export const UPDATE_LEAVE_BANK_SUCCESS = 'UPDATE_LEAVE_BANK_SUCCESS';
export const UPDATE_LEAVE_BANK_ERROR = 'UPDATE_LEAVE_BANK_ERROR';

export const DELETE_LEAVE_BANK_START = 'DELETE_LEAVE_BANK_START';
export const DELETE_LEAVE_BANK_SUCCESS = 'DELETE_LEAVE_BANK_SUCCESS';
export const DELETE_LEAVE_BANK_ERROR = 'DELETE_LEAVE_BANK_ERROR';


//getting all experts 
export const LOAD_ALL_EXPERTS_START = 'LOAD_ALL_EXPERTS_START';
export const LOAD_ALL_EXPERTS_SUCCESS = 'LOAD_ALL_EXPERTS_SUCCESS';
export const LOAD_ALL_EXPERTS_ERROR = 'LOAD_ALL_EXPERTS_ERROR';

//getting all mangment  experts 
export const LOAD_ALL_MANGEMENT_START = 'LOAD_ALL_MANGEMENT_START';
export const LOAD_ALL_MANGEMENT_SUCCESS = 'LOAD_ALL_MANGEMENT_SUCCESS';
export const LOAD_ALL_MANGEMENT_ERROR = 'LOAD_ALL_MANGEMENT_ERROR';

//mangment dashboard details actions
export const LOAD_DASHBOARDMANGEMENT_DETAILS_START = "LOAD_DASHBOARDMANGEMENT_DETAILS_START";
export const LOAD_DASHBOARDMANGEMENT_DETAILS_SUCCESS = "LOAD_DASHBOARDMANGEMENT_DETAILS_SUCCESS";
export const LOAD_DASHBOARDMANGEMENT_DETAILS_ERROR = "LOAD_DASHBOARDMANGEMENT_DETAILS_ERROR";


 //expert Dmerits details
export const CREATE_DMERITS_DETAILS_START= 'CREATE_DMERITS_DETAILS_START';
export const CREATE_DMERITS_DETAILS_SUCCESS = 'CREATE_DMERITS_DETAILS_SUCCESS';
export const CREATE_DMERITS_DETAILS_ERROR = 'CREATE_DMERITS_DETAILS_ERROR';

export const LOAD_DMERITS_DETAILS_START = 'LOAD_DMERITS_DETAILS_START';
export const LOAD_DMERITS_DETAILS_SUCCESS = 'LOAD_DMERITS_DETAILS_SUCCESS';
export const LOAD_DMERITS_DETAILS_ERROR = 'LOAD_DMERITS_DETAILS_ERROR';

export const UPDATE_DMERITS_DETAILS_START = 'UPDATE_DMERITS_DETAILS_START';
export const UPDATE_DMERITS_DETAILS_SUCCESS = 'UPDATE_DMERITS_DETAILS_SUCCESS';
export const UPDATE_DMERITS_DETAILS_ERROR = 'UPDATE_DMERITS_DETAILS_ERROR';

//expert Dmerits details
export const CREATE_PERFORMANCE_DETAILS_START= 'CREATE_PERFORMANCE_DETAILS_START';
export const CREATE_PERFORMANCE_DETAILS_SUCCESS = 'CREATE_PERFORMANCE_DETAILS_SUCCESS';
export const CREATE_PERFORMANCE_DETAILS_ERROR = 'CREATE_PERFORMANCE_DETAILS_ERROR';

export const LOAD_PERFORMANCE_DETAILS_START = 'LOAD_PERFORMANCE_DETAILS_START';
export const LOAD_PERFORMANCE_DETAILS_SUCCESS = 'LOAD_PERFORMANCE_DETAILS_SUCCESS';
export const LOAD_PERFORMANCE_DETAILS_ERROR = 'LOAD_PERFORMANCE_DETAILS_ERROR';

export const UPDATE_PERFORMANCE_DETAILS_START = 'UPDATE_PERFORMANCE_DETAILS_START';
export const UPDATE_PERFORMANCE_DETAILS_SUCCESS = 'UPDATE_PERFORMANCE_DETAILS_SUCCESS';
export const UPDATE_PERFORMANCE_DETAILS_ERROR = 'UPDATE_PERFORMANCE_DETAILS_ERROR';

//expert releaving details
export const CREATE_RELEAVING_DETAILS_START= 'CREATE_RELEAVING_DETAILS_START';
export const CREATE_RELEAVING_DETAILS_SUCCESS = 'CREATE_RELEAVING_DETAILS_SUCCESS';
export const CREATE_RELEAVING_DETAILS_ERROR = 'CREATE_RELEAVING_DETAILS_ERROR';

export const LOAD_RELEAVING_DETAILS_START = 'LOAD_RELEAVING_DETAILS_START';
export const LOAD_RELEAVING_DETAILS_SUCCESS = 'LOAD_RELEAVING_DETAILS_SUCCESS';
export const LOAD_RELEAVING_DETAILS_ERROR = 'LOAD_RELEAVING_DETAILS_ERROR';

export const UPDATE_RELEAVING_DETAILS_START = 'UPDATE_RELEAVING_DETAILS_START';
export const UPDATE_RELEAVING_DETAILS_SUCCESS = 'UPDATE_RELEAVING_DETAILS_SUCCESS';
export const UPDATE_RELEAVING_DETAILS_ERROR = 'UPDATE_RELEAVING_DETAILS_ERROR';


//expert leave Requests details
export const CREATE_LEAVEREQUESTS_DETAILS_START= 'CREATE_LEAVEREQUESTS_DETAILS_START';
export const CREATE_LEAVEREQUESTS_DETAILS_SUCCESS = 'CREATE_LEAVEREQUESTS_DETAILS_SUCCESS';
export const CREATE_LEAVEREQUESTS_DETAILS_ERROR = 'CREATE_LEAVEREQUESTS_DETAILS_ERROR';

export const LOAD_LEAVEREQUESTS_DETAILS_START = 'LOAD_LEAVEREQUESTS_DETAILS_START';
export const LOAD_LEAVEREQUESTS_DETAILS_SUCCESS = 'LOAD_LEAVEREQUESTS_DETAILS_SUCCESS';
export const LOAD_LEAVEREQUESTS_DETAILS_ERROR = 'LOAD_LEAVEREQUESTS_DETAILS_ERROR';

export const UPDATE_LEAVEREQUESTS_DETAILS_START = 'UPDATE_LEAVEREQUESTS_DETAILS_START';
export const UPDATE_LEAVEREQUESTS_DETAILS_SUCCESS = 'UPDATE_LEAVEREQUESTS_DETAILS_SUCCESS';
export const UPDATE_LEAVEREQUESTS_DETAILS_ERROR = 'UPDATE_LEAVEREQUESTS_DETAILS_ERROR';



//expert certification details
export const CREATE_CERTIFICATE_DETAILS_START= 'CREATE_CERTIFICATE_DETAILS_START';
export const CREATE_CERTIFICATE_DETAILS_SUCCESS = 'CREATE_CERTIFICATE_DETAILS_SUCCESS';
export const CREATE_CERTIFICATE_DETAILS_ERROR = 'CREATE_CERTIFICATE_DETAILS_ERROR';

export const LOAD_CERTIFICATE_DETAILS_START = 'LOAD_CERTIFICATE_DETAILS_START';
export const LOAD_CERTIFICATE_DETAILS_SUCCESS = 'LOAD_CERTIFICATE_DETAILS_SUCCESS';
export const LOAD_CERTIFICATE_DETAILS_ERROR = 'LOAD_CERTIFICATE_DETAILS_ERROR';

export const UPDATE_CERTIFICATE_DETAILS_START = 'UPDATE_CERTIFICATE_DETAILS_START';
export const UPDATE_CERTIFICATE_DETAILS_SUCCESS = 'UPDATE_CERTIFICATE_DETAILS_SUCCESS';
export const UPDATE_CERTIFICATE_DETAILS_ERROR = 'UPDATE_CERTIFICATE_DETAILS_ERROR';


//expert Birthday details
export const LOAD_BIRTHDAY_DETAILS_START = 'LOAD_BIRTHDAY_DETAILS_START';
export const LOAD_BIRTHDAY_DETAILS_SUCCESS = 'LOAD_BIRTHDAY_DETAILS_SUCCESS';
export const LOAD_BIRTHDAY_DETAILS_ERROR = 'LOAD_BIRTHDAY_DETAILS_ERROR';


//expert Project details
export const CREATE_PROJECT_DETAILS_START= 'CREATE_PROJECT_DETAILS_START';
export const CREATE_PROJECT_DETAILS_SUCCESS = 'CREATE_PROJECT_DETAILS_SUCCESS';
export const CREATE_PROJECT_DETAILS_ERROR = 'CREATE_PROJECT_DETAILS_ERROR';

export const LOAD_PROJECT_DETAILS_START = 'LOAD_PROJECT_DETAILS_START';
export const LOAD_PROJECT_DETAILS_SUCCESS = 'LOAD_PROJECT_DETAILS_SUCCESS';
export const LOAD_PROJECT_DETAILS_ERROR = 'LOAD_PROJECT_DETAILS_ERROR';

export const UPDATE_PROJECT_DETAILS_START = 'UPDATE_PROJECT_DETAILS_START';
export const UPDATE_PROJECT_DETAILS_SUCCESS = 'UPDATE_PROJECT_DETAILS_SUCCESS';
export const UPDATE_PROJECT_DETAILS_ERROR = 'UPDATE_PROJECT_DETAILS_ERROR';

export const DELETE_PROJECT_DETAILS_START = 'DELETE_PROJECT_DETAILS_START';
export const DELETE_PROJECT_DETAILS_SUCCESS = 'DELETE_PROJECT_DETAILS_SUCCESS';
export const DELETE_PROJECT_DETAILS_ERROR = 'DELETE_PROJECT_DETAILS_ERROR';


//company Holidays  details
export const CREATE_HOLIDAYS_DETAILS_START= 'CREATE_HOLIDAYS_DETAILS_START';
export const CREATE_HOLIDAYS_DETAILS_SUCCESS = 'CREATE_HOLIDAYS_DETAILS_SUCCESS';
export const CREATE_HOLIDAYS_DETAILS_ERROR = 'CREATE_HOLIDAYS_DETAILS_ERROR';

export const LOAD_HOLIDAYS_DETAILS_START = 'LOAD_HOLIDAYS_DETAILS_START';
export const LOAD_HOLIDAYS_DETAILS_SUCCESS = 'LOAD_HOLIDAYS_DETAILS_SUCCESS';
export const LOAD_HOLIDAYS_DETAILS_ERROR = 'LOAD_HOLIDAYS_DETAILS_ERROR';

export const UPDATE_HOLIDAYS_DETAILS_START = 'UPDATE_HOLIDAYS_DETAILS_START';
export const UPDATE_HOLIDAYS_DETAILS_SUCCESS = 'UPDATE_HOLIDAYS_DETAILS_SUCCESS';
export const UPDATE_HOLIDAYS_DETAILS_ERROR = 'UPDATE_HOLIDAYS_DETAILS_ERROR';

export const DELETE_HOLIDAYS_DETAILS_START = 'DELETE_HOLIDAYS_DETAILS_START';
export const DELETE_HOLIDAYS_DETAILS_SUCCESS = 'DELETE_HOLIDAYS_DETAILS_SUCCESS';
export const DELETE_HOLIDAYS_DETAILS_ERROR = 'DELETE_HOLIDAYS_DETAILS_ERROR';


//company schedules and event  details
export const CREATE_EVENTMAN_DETAILS_START= 'CREATE_EVENTMAN_DETAILS_START';
export const CREATE_EVENTMAN_DETAILS_SUCCESS = 'CREATE_EVENTMAN_DETAILS_SUCCESS';
export const CREATE_EVENTMAN_DETAILS_ERROR = 'CREATE_EVENTMAN_DETAILS_ERROR';

export const LOAD_EVENTMAN_DETAILS_START = 'LOAD_EVENTMAN_DETAILS_START';
export const LOAD_EVENTMAN_DETAILS_SUCCESS = 'LOAD_EVENTMAN_DETAILS_SUCCESS';
export const LOAD_EVENTMAN_DETAILS_ERROR = 'LOAD_EVENTMAN_DETAILS_ERROR';

export const UPDATE_EVENTMAN_DETAILS_START = 'UPDATE_EVENTMAN_DETAILS_START';
export const UPDATE_EVENTMAN_DETAILS_SUCCESS = 'UPDATE_EVENTMAN_DETAILS_SUCCESS';
export const UPDATE_EVENTMAN_DETAILS_ERROR = 'UPDATE_EVENTMAN_DETAILS_ERROR';

export const DELETE_EVENTMAN_DETAILS_START = 'DELETE_EVENTMAN_DETAILS_START';
export const DELETE_EVENTMAN_DETAILS_SUCCESS = 'DELETE_EVENTMAN_DETAILS_SUCCESS';
export const DELETE_EVENTMAN_DETAILS_ERROR = 'DELETE_EVENTMAN_DETAILS_ERROR';



// experts Gadgets Details
export const CREATE_GADGETS_DETAILS_START= 'CREATE_GADGETS_DETAILS_START';
export const CREATE_GADGETS_DETAILS_SUCCESS = 'CREATE_GADGETS_DETAILS_SUCCESS';
export const CREATE_GADGETS_DETAILS_ERROR = 'CREATE_GADGETS_DETAILS_ERROR';

export const LOAD_GADGETS_DETAILS_START = 'LOAD_GADGETS_DETAILS_START';
export const LOAD_GADGETS_DETAILS_SUCCESS = 'LOAD_GADGETS_DETAILS_SUCCESS';
export const LOAD_GADGETS_DETAILS_ERROR = 'LOAD_GADGETS_DETAILS_ERROR';

export const UPDATE_GADGETS_DETAILS_START = 'UPDATE_GADGETS_DETAILS_START';
export const UPDATE_GADGETS_DETAILS_SUCCESS = 'UPDATE_GADGETS_DETAILS_SUCCESS';
export const UPDATE_GADGETS_DETAILS_ERROR = 'UPDATE_GADGETS_DETAILS_ERROR';

export const DELETE_GADGETS_DETAILS_START = 'DELETE_GADGETS_DETAILS_START';
export const DELETE_GADGETS_DETAILS_SUCCESS = 'DELETE_GADGETS_DETAILS_SUCCESS';
export const DELETE_GADGETS_DETAILS_ERROR = 'DELETE_GADGETS_DETAILS_ERROR';


// experts proficiency Details
export const LOAD_PROFICIENCY_DETAILS_START= 'LOAD_PROFICIENCY_DETAILS_START';
export const LOAD_PROFICIENCY_DETAILS_SUCCESS = 'LOAD_PROFICIENCY_DETAILS_SUCCESS';
export const LOAD_PROFICIENCY_DETAILS_ERROR = 'LOAD_PROFICIENCY_DETAILS_ERROR';

export const LOAD_PROFICIENCYSELECT_DETAILS_START= 'LOAD_PROFICIENCYSELECT_DETAILS_START';
export const LOAD_PROFICIENCYSELECT_DETAILS_SUCCESS = 'LOAD_PROFICIENCYSELECT_DETAILS_SUCCESS';
export const LOAD_PROFICIENCYSELECT_DETAILS_ERROR = 'LOAD_PROFICIENCYSELECT_DETAILS_ERROR';


// experts Weekly Status Details
export const LOAD_WEEKLY_DETAILS_START= 'LOAD_WEEKLY_DETAILS_START';
export const LOAD_WEEKLY_DETAILS_SUCCESS = 'LOAD_WEEKLY_DETAILS_SUCCESS';
export const LOAD_WEEKLY_DETAILS_ERROR = 'LOAD_WEEKLY_DETAILS_ERROR';

export const LOAD_WEEKLYSELECT_DETAILS_START= 'LOAD_WEEKLYSELECT_DETAILS_START';
export const LOAD_WEEKLYSELECT_DETAILS_SUCCESS = 'LOAD_WEEKLYSELECT_DETAILS_SUCCESS';
export const LOAD_WEEKLYSELECT_DETAILS_ERROR = 'LOAD_WEEKLYSELECT_DETAILS_ERROR';


// experts all names users
export const LOAD_AllUSERS_DETAILS_START= 'LOAD_AllUSERS_DETAILS_START';
export const LOAD_AllUSERS_DETAILS_SUCCESS = 'LOAD_AllUSERS_DETAILS_SUCCESS';
export const LOAD_AllUSERS_DETAILS_ERROR = 'LOAD_AllUSERS_DETAILS_ERROR';


// experts Monthly Status Details
export const LOAD_MONTHLY_DETAILS_START= 'LOAD_MONTHLY_DETAILS_START';
export const LOAD_MONTHLY_DETAILS_SUCCESS = 'LOAD_MONTHLY_DETAILS_SUCCESS';
export const LOAD_MONTHLY_DETAILS_ERROR = 'LOAD_MONTHLY_DETAILS_ERROR';


// experts Monthly Attendence list Details
export const LOAD_MONTHLYATTENDENCELIST_DETAILS_START= 'LOAD_MONTHLYATTENDENCELIST_DETAILS_START';
export const LOAD_MONTHLYATTENDENCELIST_DETAILS_SUCCESS = 'LOAD_MONTHLYATTENDENCELIST_DETAILS_SUCCESS';
export const LOAD_MONTHLYATTENDENCELIST_DETAILS_ERROR = 'LOAD_MONTHLYATTENDENCELIST_DETAILS_ERROR';

export const CREATE_PAYSLIP_DETAILS_START= 'CREATE_PAYSLIP_DETAILS_START';
export const CREATE_PAYSLIP_DETAILS_SUCCESS = 'CREATE_PAYSLIP_DETAILS_SUCCESS';
export const CREATE_PAYSLIP_DETAILS_ERROR = 'CREATE_GADGETS_DETAILS_ERROR';

export const STORE_API_RESULT = 'STORE_API_RESULT';

// experts Gadgets Details
export const CREATE_ATTENDENCELIST_DETAILS_START= 'CREATE_ATTENDENCELIST_DETAILS_START';
export const CREATE_ATTENDENCELIST_DETAILS_SUCCESS = 'CREATE_ATTENDENCELIST_DETAILS_SUCCESS';
export const CREATE_ATTENDENCELIST_DETAILS_ERROR = 'CREATE_ATTENDENCELIST_DETAILS_ERROR';

export const LOAD_ATTENDENCELIST_DETAILS_START = 'LOAD_ATTENDENCELIST_DETAILS_START';
export const LOAD_ATTENDENCELIST_DETAILS_SUCCESS = 'LOAD_ATTENDENCELIST_DETAILS_SUCCESS';
export const LOAD_ATTENDENCELIST_DETAILS_ERROR = 'LOAD_ATTENDENCELIST_DETAILS_ERROR';

export const UPDATE_ATTENDENCELIST_DETAILS_START = 'UPDATE_ATTENDENCELIST_DETAILS_START';
export const UPDATE_ATTENDENCELIST_DETAILS_SUCCESS = 'UPDATE_ATTENDENCELIST_DETAILS_SUCCESS';
export const UPDATE_ATTENDENCELIST_DETAILS_ERROR = 'UPDATE_ATTENDENCELIST_DETAILS_ERROR';


// experts personalwise Details

export const LOAD_PERSONALWISE_DETAILS_START = 'LOAD_PERSONALWISE_DETAILS_START';
export const LOAD_PERSONALWISE_DETAILS_SUCCESS = 'LOAD_PERSONALWISE_DETAILS_SUCCESS';
export const LOAD_PERSONALWISE_DETAILS_ERROR = 'LOAD_PERSONALWISE_DETAILS_ERROR';

export const LOAD_EMERGENCYWISE_DETAILS_START = 'LOAD_EMERGENCYWISE_DETAILS_START';
export const LOAD_EMERGENCYWISE_DETAILS_SUCCESS = 'LOAD_EMERGENCYWISE_DETAILS_SUCCESS';
export const LOAD_EMERGENCYWISE_DETAILS_ERROR = 'LOAD_EMERGENCYWISE_DETAILS_ERROR';

export const LOAD_FAMILYWISE_DETAILS_START = 'LOAD_FAMILYWISE_DETAILS_START';
export const LOAD_FAMILYWISE_DETAILS_SUCCESS = 'LOAD_FAMILYWISE_DETAILS_SUCCESS';
export const LOAD_FAMILYWISE_DETAILS_ERROR = 'LOAD_FAMILYWISE_DETAILS_ERROR';

export const LOAD_SKILLWISE_DETAILS_START = 'LOAD_SKILLWISE_DETAILS_START';
export const LOAD_SKILLWISE_DETAILS_SUCCESS = 'LOAD_SKILLWISE_DETAILS_SUCCESS';
export const LOAD_SKILLWISE_DETAILS_ERROR = 'LOAD_SKILLWISE_DETAILS_ERROR';

export const LOAD_WORKEXPERIENCEWISE_DETAILS_START = 'LOAD_WORKEXPERIENCEWISE_DETAILS_START';
export const LOAD_WORKEXPERIENCEWISE_DETAILS_SUCCESS = 'LOAD_WORKEXPERIENCEWISE_DETAILS_SUCCESS';
export const LOAD_WORKEXPERIENCEWISE_DETAILS_ERROR = 'LOAD_WORKEXPERIENCEWISE_DETAILS_ERROR';

export const LOAD_BANKWISE_DETAILS_START = 'LOAD_BANKWISE_DETAILS_START';
export const LOAD_BANKWISE_DETAILS_SUCCESS = 'LOAD_BANKWISE_DETAILS_SUCCESS';
export const LOAD_BANKWISE_DETAILS_ERROR = 'LOAD_BANKWISE_DETAILS_ERROR';

export const LOAD_PROJECTSWISE_DETAILS_START = 'LOAD_PROJECTSWISE_DETAILS_START';
export const LOAD_PROJECTSWISE_DETAILS_SUCCESS = 'LOAD_PROJECTSWISE_DETAILS_SUCCESS';
export const LOAD_PROJECTSWISE_DETAILS_ERROR = 'LOAD_PROJECTSWISE_DETAILS_ERROR';

export const LOAD_LEAVEBANKWISE_DETAILS_START = 'LOAD_LEAVEBANKWISE_DETAILS_START';
export const LOAD_LEAVEBANKWISE_DETAILS_SUCCESS = 'LOAD_LEAVEBANKWISE_DETAILS_SUCCESS';
export const LOAD_LEAVEBANKWISE_DETAILS_ERROR = 'LOAD_LEAVEBANKWISE_DETAILS_ERROR';

export const LOAD_USER_PROFILE_DETAILS_START = 'LOAD_USER_PROFILE_DETAILS_START';
export const LOAD_USER_PROFILE_DETAILS_SUCCESS = 'LOAD_USER_PROFILE_DETAILS_SUCCESS';
export const LOAD_USER_PROFILE_DETAILS_ERROR = 'LOAD_USER_PROFILE_DETAILS_ERROR';

